name: Build Workflow

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      productName:
        description: Product name
        required: true
        type: string
      buildType:
        description: Build type (e.g., full, incremental)
        required: false
        type: string
        default: full
      skipTests:
        description: Skip tests?
        required: false
        type: boolean
        default: false
      deployAfterBuild:
        description: Deploy after build? (manual trigger only)
        required: false
        type: boolean
        default: false
      deployVersion:
        description: Version to deploy (used only if deployAfterBuild is true)
        required: false
        type: string
        default: latest
      deployConfiguration:
        description: Configuration (release/debug)
        required: false
        type: string
        default: release
      deployTarget:
        description: Deploy targets (comma separated)
        required: false
        type: string
        default: optional

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          echo "Product: ${{ inputs.productName }}"
          echo "Build type: ${{ inputs.buildType }}"
          echo "Skip tests: ${{ inputs.skipTests }}"

  maybe-deploy:
    if: github.event_name != 'workflow_dispatch' || inputs.deployAfterBuild == true
    needs: build
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      productName: ${{ inputs.productName }}
      deployVersion: ${{ inputs.deployVersion }}
      deployConfiguration: ${{ inputs.deployConfiguration }}
      deployTarget: ${{ inputs.deployTarget }}
