name: Build Workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:      
      buildType:
        type: string
        required: false
        default: full
      CONFIGURATION:
        type: string
        required: false
        default: release
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          echo "Build type: ${{ inputs.buildType }}"
          echo "CONFIGURATION type: ${{ inputs.CONFIGURATION }}"
          
  maybe-deploy:
    if: github.event_name != 'workflow_dispatch' || inputs.deployAfterBuild == true
    needs: build
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      deployVersion: ${{ inputs.deployVersion }}
      deployTarget: ${{ inputs.deployTarget }}
