name: Build Workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      productName:
        type: string
        required: true
      
      buildType:
        type: string
        required: false
        default: full
      
      skipTests:
        type: boolean
        required: false
        default: false
      
      deployAfterBuild:
        type: boolean
        required: false
        default: false

      deployVersion:
        type: string
        required: false

      deployConfiguration:
        type: string
        required: false
        default: release

      deployTarget:
        type: string
        required: false
        default: optional


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          echo "Product: ${{ inputs.productName }}"
          echo "Build type: ${{ inputs.buildType }}"
          echo "Skip tests: ${{ inputs.skipTests }}"

  maybe-deploy:
    if: github.event_name != 'workflow_dispatch' || inputs.deployAfterBuild == true
    needs: build
    uses: ngarg1234/cs-prof-common-utilities/.github/workflows/deploy.yaml@master
    with:
      productName: ${{ inputs.productName }}
      deployVersion: ${{ inputs.deployVersion }}
      deployConfiguration: ${{ inputs.deployConfiguration }}
      deployTarget: ${{ inputs.deployTarget }}
