name: Deploy Workflow
 
on:
  workflow_call:
    inputs:
      deployVersion:
        required: false
        type: string
      deployTarget:
        required: false
        type: string
 
jobs:
  deploy:
    name: Deploy APP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Simulate Deployment
        run: |
          echo "Version: ${{ inputs.deployVersion }}"
          echo "Target: ${{ inputs.deployTarget }}"
